trigger:
- master
- release/*

# See https://github.com/dotnet/arcade
resources:
  repositories:
  - repository: arcade
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: dotnet/arcade
    ref: refs/heads/master

phases:
- phase: Helix
  queue:
    name: DotNetCore-Windows
    timeoutInMinutes: 120

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      projects: eng/common/helixpublish.proj
      custom: msbuild
      arguments: '/t:test /p:Language=msbuild'
    displayName: Send tests job to Helix
    env:
      HelixSource: your/helix/source
      HelixType: type/tests
      HelixBuild: $(Build.BuildNumber)
      HelixTargetQueues: Windows.10.Amd64.Open;Windows.7.Amd64.Open
      HelixAccessToken: $('BotAccount-dotnet-github-anon-kaonashi-bot-helix-token')
      HelixPreCommands: ''
      HelixPostCommands: ''
      WorkItemDirectory: tests
      WorkItemCommand: runtests.cmd
      EnableXUnitReporter: true
      WaitForWorkItemCompletion: true