trigger:
- master
- release/*

# See https://github.com/dotnet/arcade
resources:
  repositories:
  - repository: arcade
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: dotnet/arcade
    ref: refs/heads/master

phases:
- phase: Helix
  queue:
    name: DotNetCore-Windows
    timeoutInMinutes: 120
- template: eng/common/templates/steps/helix-publish.yml@arcade
  parameters:
    HelixSource: your/helix/source
    HelixType: type/tests
    # HelixBuild: $(Build.BuildNumber) -- This property is set by default
    HelixTargetQueues: Windows.10.Amd64.Open;Windows.7.Amd64.Open
    HelixAccessToken: $('BotAccount-dotnet-github-anon-kaonashi-bot-helix-token')
    # HelixPreCommands: '' -- any commands that you would like to run prior to running your job
    # HelixPostCommands: '' -- any commands that you would like to run after running your job
    WorkItemDirectory: tests
    WorkItemCommand: runtests.cmd
    EnableXUnitReporter: true # required for reporting out XUnit test results
    # WaitForWorkItemCompletion: true -- defaults to true
